services:
  - type: web
    name: orvba-app
    env: docker
    plan: free
    region: oregon
    buildCommand: php artisan migrate --force 
    envVars:
      - key: APP_SERVICE_TYPE
        value: web
      - fromDatabase:
          name: orvba-db
          property: connectionString
        key: DATABASE_URL
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: orvba-db
          property: connectionString
      - key: REVERB_HOST
        sync: false
      - key: REVERB_APP_ID
        generateValue: true
      - key: REVERB_APP_KEY
        generateValue: true
      - key: REVERB_APP_SECRET
        generateValue: true
      - key: REVERB_SCHEME
        value: https
      - key: REVERB_PORT
        value: 443

databases:
  - name: orvba-db
    plan: free
    region: oregon
